#!/bin/sh

fancy_echo "Installing zsh..."

# Make ~/.zshrc if it does not exsit
if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

append_to_file "$HOME/.zshrc" 'export PATH="$HOME/.bin:$PATH"'

# Unless shell is not already Zsh or if running Continuous Integration system,
# set shell to Zsh
case "$SHELL" in
  */zsh) : ;;
  *)
    if [ -z "$CI" ]; then
      fancy_echo "Changing your shell to zsh ..."
      sudo dscl . change /users/$USER UserShell /bin/bash $(which zsh)
    else
      fancy_echo "CI System detected, will not change shells"
    fi
    ;;
esac

echo "Setting up z directory navigation..."
echo "# z directory navigation" >> ~/.zshrc
echo ". /usr/local/etc/profile.d/z.sh" >> ~/.zshrc
touch ~/.z
echo "...z has been configured"

fancy_echo "...Finsihed zsh installation"
