cask_args appdir: '/Applications'

# taps are Formulaes/commands pulled from a Git repo
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/services'

# brew is used for installing MacOS dependencies/binaries
brew 'bash'
brew 'git'
brew 'git-secrets'
# brew 'java8'
brew 'gradle'
brew 'heroku-toolbelt'

brew 'postgresql'
brew 'mysql'

brew 'vim'

brew 'zsh'
brew 'z'

# start psql cluster
# brew services start postgresql

# start mysql cluster
# brew services start mysql
