cask_args appdir: '/Applications'

# taps are Formulaes/commands pulled from a Git repo
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/services'

# brew is used for installing MacOS dependencies/binaries
brew 'bash'
brew 'git'
brew 'vim'
brew 'zsh'
brew 'z'

brew 'gradle'
brew 'heroku/brew/heroku'
brew 'postgresql'
brew 'mysql'

brew 'homebrew/cask-drivers/luna-display'


# start psql cluster
# brew services start postgresql

# start mysql cluster
# brew services start mysql
