#!/bin/sh

fancy_echo "Bundling antigen plugins ..."

# Load oh-my-zsh as default repo for antigen
antigen use oh-my-zsh

# Oh-my-zsh/default bundles
antigen bundle git
antigen bundle git-extras
antigen bundle heroku
antigen bundle httpie
antigen bundle jsontools
antigen bundle lol
antigen bundle node
antigen bundle pip
antigen bundle web-search

# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting

# Themes
antigen theme agnoster

# Says your done
antigen apply
